services:
  app-server:
    image: node-socketio-cluster-server
    build:
      target: deploy-server
    ports:
      - '3000:3000'
    environment:
      - COMPOSE_BAKE    
  app-client:
    image: node-socketio-cluster-client
    build:
      target: deploy-client
    ports:
      - 5173:80
    environment:
      - COMPOSE_BAKE
